baseURL = "/"
title = "tbsmcd"
theme ="hugo-xmin"
languageCode = "ja"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

hasCJKLanguage = true
showFooterCredits = true

[params]
footer = "[Posts](/) | [Tags](/tags/) | [Feed](/index.xml) | [MOCHIDA Tsubasa @tbsmcd](/about/)"

useIcon = true
useTwitterCard = true

math = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
