baseURL = "/"
title = "tbsmcd.net"
theme ="hugo-xmin"
languageCode = "ja"
googleAnalytics = "UA-158035573-1"
enableEmoji = true 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

hasCJKLanguage = true
showFooterCredits = true

# シンタックスハイライトを有効に
pygmentsUseClasses = true
# github 風に ``` で囲む
pygmentsCodefences = true

[params]
header = "tbsmcd.net [<span>index</span>](/), [<span>archives</span>](/archives/), [<span>tags</span>](/tags/), [<span>search</span>](/search/), [<span>profile</span>](/profile/)"
footer = "Written by Mochida Tsubasa(@tbsmcd). [Contact](https://docs.google.com/forms/d/e/1FAIpQLScLrngN5Znk15zTy06N9qjO3Mi_ubIrXrX9cfYFid_2-mmbQQ/viewform) [Feed](/index.xml)"

useIcon = true
useTwitterCard = true

math = true

[taxonomies]
tag = "tags"
archive = "archives"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["html", "json", "rss"]
