baseURL = "/"
title = "tbsmcd"
theme ="hugo-xmin"
languageCode = "ja"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

hasCJKLanguage = true
showFooterCredits = true

[params]
footer = "[Home](/) | [Archives](/archives/) | [Tags](/tags/) | [Feed](/index.xml) | [tbsmcd](/about/)"

useIcon = true
useTwitterCard = true

math = true

